export const ALL_LOGIN_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_LOGIN_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_LOGIN_FAILURE = "ALL_PRODUCT_FAILURE";
export const CLEAR_ERROR = "CLEAR_ERROR";
