export const ALL_LOGIN_REQUEST = "ALL_LOGIN_REQUEST";
export const ALL_LOGIN_SUCCESS = "ALL_LOGIN_SUCCESS";
export const ALL_LOGIN_FAILURE = "ALL_LOGIN_FAILURE";

export const ALL_SIGNUP_USER_REQUEST =
  "ALL_SIGNUP_USER_REQUEST";
export const ALL_SIGNUP_USER_SUCCESS =
  "ALL_SIGNUP_USER_SUCCESS";
export const ALL_SIGNUP_USER_FAILURE =
  "ALL_SIGNUP_USER_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILURE = "LOG_OUT_FAILURE";

export const UPDATE_PROFILE_REQUEST =
  "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS =
  "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE =
  "UPDATE_PROFILE_FAILURE";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const UPDATE_PASSWORD_REQUEST =
  "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS =
  "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE =
  "UPDATE_PASSWORD_FAILURE";
export const UPDATE_PASSWORD_RESET =
  "UPDATE_PASSWORD_RESET";

export const FORGOT_PASSWORD_REQUEST =
  "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS =
  "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE =
  "FORGOT_PASSWORD_FAILURE";

export const CLEAR_ERROR = "CLEAR_ERROR";
