export const ALL_LOGIN_REQUEST = "ALL_LOGIN_REQUEST";
export const ALL_LOGIN_SUCCESS = "ALL_LOGIN_SUCCESS";
export const ALL_LOGIN_FAILURE = "ALL_LOGIN_FAILURE";

export const ALL_SIGNUP_USER_REQUEST =
  "ALL_SIGNUP_USER_REQUEST";
export const ALL_SIGNUP_USER_SUCCESS =
  "ALL_SIGNUP_USER_SUCCESS";
export const ALL_SIGNUP_USER_FAILURE =
  "ALL_SIGNUP_USER_FAILURE";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const CLEAR_ERROR = "CLEAR_ERROR";
